version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:80" # Maps port 80 inside the container to 8080 on the host
  backend:
    build:
      context: .
      network: host
      dockerfile: Dockerfile-bkp
      target: backend-runner
    environment:
      - PYTHONPATH=/lib:$PYTHONPATH
    ports:
      - "8082:8082"

